FROM registry.fedoraproject.org/fedora:latest@sha256:5c4a3effc6a2877782981a1c8fccf0cf57ac73da0d63d3e50d73a34a4686a444

COPY mock-wrapper /usr/bin

RUN dnf install -y mock rpmdevtools rpkg copr-cli rpmlint && dnf clean all

ENTRYPOINT ["/usr/bin/mock-wrapper"]
