#!/bin/bash
set -euo pipefail

SENTINEL_FILE="/var/lib/ublue-os/fw-fanctrl"
VEN_ID="$(cat /sys/devices/virtual/dmi/id/chassis_vendor || echo "")"

if [[ ":Framework:" =~ :$VEN_ID: ]]; then
  echo "Framework Laptop detected. Enabling fw-fanctrl.service."
  systemctl enable --now fw-fanctrl.service

  mkdir -p "$(dirname "$SENTINEL_FILE")"
  touch "$SENTINEL_FILE"
else
  echo "Not a Framework device"
fi
