test-local:
  #!/bin/bash
  set -eo pipefail

  if [[ -z "$GITHUB_TOKEN" ]]; then
    echo 'Must set $GITHUB_TOKEN environment variable'
    exit 1
  fi

  tmpdir=$(mktemp -d)
  chmod og+rx $tmpdir
  echo "Working in $tmpdir"
  cp -r ../../* ../../.* $tmpdir
  podman run -it --rm -v ${tmpdir}:/usr/src/app --security-opt label=disable -u root \
    -e RENOVATE_TOKEN=$GITHUB_TOKEN \
    -e GITHUB_TOKEN=$GITHUB_TOKEN \
    renovate/renovate:39 /usr/bin/python3 /usr/src/app/test/renovate/test_renovate.py
  rm -rf $tmpdir
