package:
  name: bluefin-base
  version: 0.0.0
  epoch: 0
  description: "Bluefin metapackage"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - atuin
      - brew
      - gawk
      - eza
      - fd
      - fish
      - fzf
      - rclone
      - ripgrep
      - sed
      - starship
      - ublue-base
      - zoxide
      - zsh

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - curl

pipeline:
  - runs: |
      # Symlink linuxbrew to homebrew
      mkdir -p "${{targets.destdir}}"/home
      ln -sf /home/linuxbrew "${{targets.destdir}}"/home/homebrew

      # Install bash-prexec
      mkdir -p "${{targets.destdir}}"/usr/share
      curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o "${{targets.destdir}}"/usr/share/bash-prexec

      # Copy system files
      cp -r etc "${{targets.destdir}}"
      cp -r usr "${{targets.destdir}}"
      cp -r root "${{targets.destdir}}"

update:
  manual: true
