name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "**/*.just"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "**/*.just"

jobs:
  validate-just:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Just
        shell: bash
        run: bash .github/workflows/shared/install-just.sh
        
      - name: Check Just Syntax
        shell: bash
        run: |
          just check
