name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"
      - "**/*.just"
  push:
    branches:
      - main
    paths:
      - "Justfile"
      - "**/*.just"

jobs:
  validate-just:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install Just
        shell: bash
        run: bash .github/workflows/shared/install-just.sh
        
      - name: Check Just Syntax
        shell: bash
        run: |
          just check
